version: 2.1

jobs:
  build: # this can be any name you choose
    docker: 
     - image: circleci/python:3.6.1
    working_directory: ~/repo
    
    steps:
      - checkout # checkout source code
      
      #Download and cache directories
      - restore_cache:
         keys:
          - v1-dependencies-{{ checksum "requirements.txt"}}
          #fallbacl to the latest cache if no exact match is found
          - v1-dependencies
         
      - run:
          name: install dependencies
          command: |
           python3 -m venv venv 
           . venv/bin/activate
           make install
      - save_cache:
         paths:
          - ./venv
         key: v1-dependencies-{{ checksum "requirements.txt"}}

      - run:
        name: run lint
        command: |
            . venv/bin/activate
            make lint